### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LeanderAT** [devedse/DeveImageOptimizer#3]
Hello!

Sorry for posting in your project. I couldn't find a link to send a PM to you instead.
In another thread (SNES Mini) you wrote installing Retroactive fixed your problem. My question is where I can download this tool. I only find RetroArch for Snes Mini but not Retroactive.

Please help!

**Comment by devedse** [comment]
Oh damn, I meant retroarch, autocorrect screwed that up.

**Comment by LeanderAT** [comment]
Thanks for your quick reply! I already downloaded everyting again but it still does not work. I set up a fresh Mame copy to see what Rodland, Bubble Bobble 2 and Wizard of Wor need...they do not need a bios...so I guess the command line is wrong.

How should I set it so it works?

/bin/zip /usr/share/games/CLV-Z-NKZBT/rodland.zip

Tutorials say to change zip to fba ... or cps2... but these are for specific bios....I don't need them. Should I add -retroarch? 
Do you know the command line I need to enter?

**Comment by devedse** [comment]
I only did the following steps:
1. Download latest hakchi2
2. Open it
3. Connect NES
4. Let it flash the new kernel
5. Add some games for NES
6. Find out they don't start
7. Download RetroArch
8. Drag drop it into Hakchi2 (Don't click on add games but use drag / drop instead).
9. Select all cores you want (a core is basically an internal emulator for RetroArch), I just left it on default, not sure if MAME is enabled then.
10. Done

Ps. I think it's best if we continue talking in the initial thread.
